image: Visual Studio 2015

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QTDIR: C:\Qt\5.11\msvc2017_64
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
    PLATFORM:
  - QTDIR: C:\Qt\5.11\msvc2015
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
    PLATFORM: x86

init:
- call "%QTDIR%\bin\qtenv2.bat"
- set PATH=C:\Qt\Tools\QtCreator\bin;%PATH%
- call "%VCVARS%" %platform%
- cd /D "%APPVEYOR_BUILD_FOLDER%"

before_build:
- if defined APPVEYOR_REPO_TAG_NAME (set VERSION="%APPVEYOR_REPO_TAG_NAME%") else for /F %%I in ('git rev-list --count HEAD') do set VERSION="git%%I"
- set DEPLOY_DIR=Quaternion-%VERSION%
- git submodule update --init --recursive
- cmake -LA -G "NMake Makefiles JOM" -H. -Bbuild -DCMAKE_CXX_FLAGS="/EHsc /W3" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="%DEPLOY_DIR%" -DUSE_INTREE_LIBQMC=1 -DDEPLOY_VERBOSITY=%DEPLOY_VERBOSITY%

build_script:
- cmake --build build

after_build:
- cmake --build build --target install
- cd "%DEPLOY_DIR%"
- rmdir /S /Q bearer qmltooling
- cd ..
- 7z a quaternion-%VERSION%-windows.zip "%DEPLOY_DIR%\"

# Uncomment this to connect to the AppVeyor build worker
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test: off

artifacts:
- path: quaternion*.zip

deploy:
- provider: Environment
  name: GitHub
  on:
    APPVEYOR_REPO_TAG: true
- provider: Environment
  name: Bintray
  version: "%VERSION%"
  on:
    branch: master
